"""Add MFA and account lockout columns

Revision ID: 6790795ded86
Revises: 748b64e82832
Create Date: 2026-04-25 10:36:25.256684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6790795ded86'
down_revision = '748b64e82832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions_202012', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202012_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202012_user_id'))

    op.drop_table('transactions_202012')
    with op.batch_alter_table('transactions_202102', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202102_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202102_user_id'))

    op.drop_table('transactions_202102')
    with op.batch_alter_table('transactions_202111', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202111_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202111_user_id'))

    op.drop_table('transactions_202111')
    with op.batch_alter_table('transactions_202107', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202107_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202107_user_id'))

    op.drop_table('transactions_202107')
    with op.batch_alter_table('transactions_202007', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202007_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202007_user_id'))

    op.drop_table('transactions_202007')
    with op.batch_alter_table('transactions_202101', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202101_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202101_user_id'))

    op.drop_table('transactions_202101')
    with op.batch_alter_table('transactions_202108', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202108_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202108_user_id'))

    op.drop_table('transactions_202108')
    with op.batch_alter_table('transactions_202008', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202008_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202008_user_id'))

    op.drop_table('transactions_202008')
    with op.batch_alter_table('transactions_202011', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202011_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202011_user_id'))

    op.drop_table('transactions_202011')
    with op.batch_alter_table('transactions_202002', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202002_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202002_user_id'))

    op.drop_table('transactions_202002')
    with op.batch_alter_table('transactions_202109', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202109_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202109_user_id'))

    op.drop_table('transactions_202109')
    with op.batch_alter_table('transactions_202106', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202106_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202106_user_id'))

    op.drop_table('transactions_202106')
    with op.batch_alter_table('transactions_202105', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202105_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202105_user_id'))

    op.drop_table('transactions_202105')
    with op.batch_alter_table('transactions_202103', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202103_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202103_user_id'))

    op.drop_table('transactions_202103')
    with op.batch_alter_table('transactions_202004', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202004_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202004_user_id'))

    op.drop_table('transactions_202004')
    with op.batch_alter_table('transactions_202001', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202001_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202001_user_id'))

    op.drop_table('transactions_202001')
    with op.batch_alter_table('transactions_202006', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202006_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202006_user_id'))

    op.drop_table('transactions_202006')
    with op.batch_alter_table('transactions_202005', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202005_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202005_user_id'))

    op.drop_table('transactions_202005')
    with op.batch_alter_table('transactions_202010', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202010_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202010_user_id'))

    op.drop_table('transactions_202010')
    with op.batch_alter_table('transactions_202009', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202009_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202009_user_id'))

    op.drop_table('transactions_202009')
    with op.batch_alter_table('transactions_202110', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202110_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202110_user_id'))

    op.drop_table('transactions_202110')
    with op.batch_alter_table('transactions_202003', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202003_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202003_user_id'))

    op.drop_table('transactions_202003')
    with op.batch_alter_table('transactions_202104', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202104_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202104_user_id'))

    op.drop_table('transactions_202104')
    with op.batch_alter_table('transactions_202112', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_202112_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_202112_user_id'))

    op.drop_table('transactions_202112')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('mfa_secret')

    op.create_table('transactions_202112',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202112', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202112_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202112_date'), ['date'], unique=False)

    op.create_table('transactions_202104',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202104', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202104_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202104_date'), ['date'], unique=False)

    op.create_table('transactions_202003',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202003', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202003_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202003_date'), ['date'], unique=False)

    op.create_table('transactions_202110',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202110', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202110_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202110_date'), ['date'], unique=False)

    op.create_table('transactions_202009',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202009', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202009_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202009_date'), ['date'], unique=False)

    op.create_table('transactions_202010',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202010', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202010_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202010_date'), ['date'], unique=False)

    op.create_table('transactions_202005',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202005', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202005_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202005_date'), ['date'], unique=False)

    op.create_table('transactions_202006',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202006', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202006_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202006_date'), ['date'], unique=False)

    op.create_table('transactions_202001',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202001', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202001_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202001_date'), ['date'], unique=False)

    op.create_table('transactions_202004',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202004', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202004_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202004_date'), ['date'], unique=False)

    op.create_table('transactions_202103',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202103', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202103_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202103_date'), ['date'], unique=False)

    op.create_table('transactions_202105',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202105', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202105_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202105_date'), ['date'], unique=False)

    op.create_table('transactions_202106',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202106', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202106_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202106_date'), ['date'], unique=False)

    op.create_table('transactions_202109',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202109', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202109_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202109_date'), ['date'], unique=False)

    op.create_table('transactions_202002',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202002', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202002_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202002_date'), ['date'], unique=False)

    op.create_table('transactions_202011',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202011', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202011_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202011_date'), ['date'], unique=False)

    op.create_table('transactions_202008',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202008', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202008_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202008_date'), ['date'], unique=False)

    op.create_table('transactions_202108',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202108', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202108_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202108_date'), ['date'], unique=False)

    op.create_table('transactions_202101',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202101', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202101_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202101_date'), ['date'], unique=False)

    op.create_table('transactions_202007',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202007', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202007_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202007_date'), ['date'], unique=False)

    op.create_table('transactions_202107',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202107', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202107_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202107_date'), ['date'], unique=False)

    op.create_table('transactions_202111',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202111', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202111_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202111_date'), ['date'], unique=False)

    op.create_table('transactions_202102',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202102', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202102_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202102_date'), ['date'], unique=False)

    op.create_table('transactions_202012',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('transactions_202012', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_202012_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_202012_date'), ['date'], unique=False)

    # ### end Alembic commands ###
